server:
  port: 8080

spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  cloud:
    gateway:
      server:
        webflux:
          routes: []

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
